---
- name: Configure Nginx on EC2
  hosts: all
  become: yes
  tasks:
    - name: Detect OS version
      debug:
        msg: "Detected OS: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

    - name: Wait for yum lock to be released
      shell: |
        while sudo fuser /var/run/yum.pid >/dev/null 2>&1; do
          echo "Waiting for yum lock..."
          sleep 5
        done
      retries: 5
      delay: 10
      register: wait_result
      until: wait_result.rc == 0

    - name: Enable Nginx extras on Amazon Linux 2
      command: amazon-linux-extras enable nginx1
      when:
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version == "2"

    - name: Install Nginx on Amazon Linux 2
      yum:
        name: nginx
        state: present
      when:
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version == "2"

    - name: Install Nginx on Amazon Linux 2023 or other distros
      dnf:
        name: nginx
        state: present
      when:
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version == "2023" or ansible_pkg_mgr == "dnf"

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create Hello World page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "Hello World from nginx by Liteesh!"

